### ISSUE TITLE
Infiniband: could not get ARP entries: failed to parse ARP entry

### ISSUE THREAD

**Issue by knweiss** [prometheus/procfs#545] opened 2023-07-05 08:19 UTC
I've started testing node-exporter 1.6.0 and compare it against 1.4.1. I found a regression in the node-exporter-1.6.0's **ARP collector**. Its ARP parser is now implemented using **procfs** and the new code is not able to parse IPoIB (InfiniBand) entries in the Linux kernel ARP table.

Example:
```
# grep ib0 /proc/net/arp                                                                         
10.3.3.170       0x20        0x2         00:00:00:66:fe:80:00:00:00     *        ib0
```
The ARP collector shows the following error messages:

```
ts=2023-07-05T07:12:07.245Z caller=collector.go:169 level=error msg="collector failed" 
name=arp duration_seconds=0.015415491
err="could not get ARP entries: failed to parse ARP entry: address 00:00:00:66:fe:80:00:00:00: invalid MAC address"
```

The result is that no `node_arp_entries` metrics are collected at all on systems with Infiniband:
```
$ grep arp metrics-node-exporter-1.4.1.txt
# HELP node_arp_entries ARP entries by device
# TYPE node_arp_entries gauge
node_arp_entries{device="ib0"} 1
node_arp_entries{device="team0"} 103
node_arp_entries{device="team1"} 2
node_scrape_collector_duration_seconds{collector="arp"} 0.003099647
node_scrape_collector_success{collector="arp"} 1
$ grep arp metrics-node-exporter-1.6.0.txt
node_scrape_collector_duration_seconds{collector="arp"} 0.040095475
node_scrape_collector_success{collector="arp"} 0
```

**Comment by dswarbrick** [comment] 2023-08-17 14:59
This is caused by the fact that `/proc/net/arp` only includes the first nine bytes of the link-layer address.

cf. `net/ipv4/arp.c`:
```c
#define HBUFFERLEN 30

static void arp_format_neigh_entry(struct seq_file *seq,
				   struct neighbour *n)
{
	char hbuffer[HBUFFERLEN];
...
	for (k = 0, j = 0; k < HBUFFERLEN - 3 && j < dev->addr_len; j++) {
		hbuffer[k++] = hex_asc_hi(n->ha[j]);
		hbuffer[k++] = hex_asc_lo(n->ha[j]);
		hbuffer[k++] = ':';
	}
...
	sprintf(tbuf, "%pI4", n->primary_key);
	seq_printf(seq, "%-16s 0x%-10x0x%-10x%-17s     *        %s\n",
		   tbuf, hatype, arp_state_to_flags(n), hbuffer, dev->name);
...
}
```
`hbuffer` is only large enough to hold up to 30 chars of human-readable (hex-formatted with colons) link-layer address. This will truncate a 20-byte InfiniBand link-address, e.g. `00:00:00:00:fe:80:00:00:00:00:00:00:02:00:5e:10:00:00:00:01`, causing [net.ParseMAC()](https://pkg.go.dev/net#ParseMAC) to throw an error.

**Comment by dswarbrick** [comment] 2023-11-02 14:34
The fix for this was already merged. Issue can be closed.

**Closed** 2023-11-12 23:19 UTC
Labels: bug
