### ISSUE TITLE
Recent change removed methods required by elastic/go-sysinfo with no version number bump

### ISSUE THREAD

**Issue by jshields** [prometheus/procfs#169] opened 2019-05-31 14:57 UTC
Related to: https://github.com/prometheus/procfs/issues/167

This commit removed methods that are used by other libraries (breaking changes) while maintaining v0.0.1 as the latest "release":
https://github.com/prometheus/procfs/commit/985b82318ecc7741179e9c11a99095cd1f6965c9#diff-33838b2a8ea2f8e4311d86efea5944c5L151

I propose that this project follow semantic versioning. In the meantime, would it be possible to add the methods required by elastic/go-sysinfo back?
https://github.com/elastic/go-sysinfo/blob/master/providers/linux/boottime_linux.go

These are the specific errors:
```
../../../github.com/elastic/go-sysinfo/providers/linux/boottime_linux.go:40:17: fs.NewStat undefined (type procfs.FS has no field or method NewStat)
../../../github.com/elastic/go-sysinfo/providers/linux/host_linux.go:75:23: h.procFS.NewStat undefined (type procFS has no field or method NewStat)
../../../github.com/elastic/go-sysinfo/providers/linux/host_linux.go:93:17: fs.NewStat undefined (type procFS has no field or method NewStat)
../../../github.com/elastic/go-sysinfo/providers/linux/process_linux.go:49:23: s.procFS.NewProc undefined (type procFS has no field or method NewProc)
../../../github.com/elastic/go-sysinfo/providers/linux/process_linux.go:82:19: p.fs.NewProc undefined (type procFS has no field or method NewProc)
```

There was a partial revert of the breaking changes for the sake of client_golang here:
https://github.com/prometheus/procfs/commit/9b1831cbb3bb0a76227ba0e19bdfeba868679544

It seems the re-addition of the func `NewStat` here was meant to be bound to `(fs FS)`:
https://github.com/prometheus/procfs/commit/9b1831cbb3bb0a76227ba0e19bdfeba868679544#diff-33838b2a8ea2f8e4311d86efea5944c5R148

**Comment by SuperQ** [comment] 2019-05-31 16:15
Duplicate of https://github.com/prometheus/procfs/issues/98

**Comment by pgier** [comment] 2019-05-31 16:19
Reopening for re-adding the removed functions.
The semver discussion can be handled in #98

**Comment by pgier** [comment] 2019-05-31 16:28
> It seems the re-addition of the func NewStat here was meant to be bound to (fs FS):
9b1831c#diff-33838b2a8ea2f8e4311d86efea5944c5R148

@jshields The previous code (v0.0.1) had both a NewStat() and fs.NewStat() functions.  client_golang is using one, and looks like you are using the other.

**Comment by pgier** [comment] 2019-05-31 18:30
@jshields can you verify that #170 fixes the issue for you?

**Comment by jshields** [comment] 2019-06-01 21:10
Thank you for the response @pgier , understood, I will attempt to verify that the issue when using [elastic/go-sysinfo](https://github.com/elastic/go-sysinfo) is resolved on Monday. PR looks good though. Cheers 👍

**Comment by pgier** [comment] 2019-06-03 02:32
Re-opening for verification

**Comment by jshields** [comment] 2019-06-03 18:31
@pgier Issue appears to be fixed on latest `master` 👍

**Closed** 2019-06-03 20:37 UTC
